app:
  telegram-token: ${TOKEN}
  retry:
    type: const
    initial-interval: 10
    max-attempts: 3
    max-interval: 10
    multiplier: 2.78
    status-codes: 429, 401, 402
  scrapper-config:
    base-url: http://localhost:8080
    links-uri: /links
    chat-uri: /tg-chat


spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

