app:
  telegram-token: ${TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

scrapper:
  baseUrl: http://localhost:8080
  linksUri: /links
  chatUri: /tg-chat
