app:
  telegram-token: ${TOKEN}
  kafka:
    bootstrap-server: localhost:29091,localhost:29092,localhost:29093
    group-id: updates-group
    auto-offset-reset: latest
    max-poll-interval-ms: 300_000
    enable-auto-commit: false
    concurrency: 1
    topic: link-updates

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

scrapper:
  baseUrl: http://localhost:8080
  linksUri: /links
  chatUri: /tg-chat
