/*
 * This file is generated by jOOQ.
 */
package edu.java.repository.jooq.tables.records;

import edu.java.repository.jooq.tables.ChatAndLink;
import java.beans.ConstructorProperties;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatAndLinkRecord extends TableRecordImpl<ChatAndLinkRecord> implements Record3<Long, Long, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>CHAT_AND_LINK.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>CHAT_AND_LINK.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>CHAT_AND_LINK.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>CHAT_AND_LINK.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>CHAT_AND_LINK.STATUS</code>.
     */
    public void setStatus(@Nullable Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>CHAT_AND_LINK.STATUS</code>.
     */
    @Nullable
    public Integer getStatus() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    @NotNull
    public Row3<Long, Long, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    @NotNull
    public Field<Long> field1() {
        return ChatAndLink.CHAT_AND_LINK.CHAT_ID;
    }

    @Override
    @NotNull
    public Field<Long> field2() {
        return ChatAndLink.CHAT_AND_LINK.LINK_ID;
    }

    @Override
    @NotNull
    public Field<Integer> field3() {
        return ChatAndLink.CHAT_AND_LINK.STATUS;
    }

    @Override
    @NotNull
    public Long component1() {
        return getChatId();
    }

    @Override
    @NotNull
    public Long component2() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer component3() {
        return getStatus();
    }

    @Override
    @NotNull
    public Long value1() {
        return getChatId();
    }

    @Override
    @NotNull
    public Long value2() {
        return getLinkId();
    }

    @Override
    @Nullable
    public Integer value3() {
        return getStatus();
    }

    @Override
    @NotNull
    public ChatAndLinkRecord value1(@NotNull Long value) {
        setChatId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatAndLinkRecord value2(@NotNull Long value) {
        setLinkId(value);
        return this;
    }

    @Override
    @NotNull
    public ChatAndLinkRecord value3(@Nullable Integer value) {
        setStatus(value);
        return this;
    }

    @Override
    @NotNull
    public ChatAndLinkRecord values(@NotNull Long value1, @NotNull Long value2, @Nullable Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChatAndLinkRecord
     */
    public ChatAndLinkRecord() {
        super(ChatAndLink.CHAT_AND_LINK);
    }

    /**
     * Create a detached, initialised ChatAndLinkRecord
     */
    @ConstructorProperties({ "chatId", "linkId", "status" })
    public ChatAndLinkRecord(@NotNull Long chatId, @NotNull Long linkId, @Nullable Integer status) {
        super(ChatAndLink.CHAT_AND_LINK);

        setChatId(chatId);
        setLinkId(linkId);
        setStatus(status);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChatAndLinkRecord
     */
    public ChatAndLinkRecord(edu.java.repository.jooq.tables.pojos.ChatAndLink value) {
        super(ChatAndLink.CHAT_AND_LINK);

        if (value != null) {
            setChatId(value.getChatId());
            setLinkId(value.getLinkId());
            setStatus(value.getStatus());
            resetChangedOnNotNull();
        }
    }
}
