/*
 * This file is generated by jOOQ.
 */
package edu.java.repository.jooq.tables;


import edu.java.repository.jooq.DefaultSchema;
import edu.java.repository.jooq.Keys;
import edu.java.repository.jooq.tables.records.ChatAndLinkRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.13"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatAndLink extends TableImpl<ChatAndLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>CHAT_AND_LINK</code>
     */
    public static final ChatAndLink CHAT_AND_LINK = new ChatAndLink();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<ChatAndLinkRecord> getRecordType() {
        return ChatAndLinkRecord.class;
    }

    /**
     * The column <code>CHAT_AND_LINK.CHAT_ID</code>.
     */
    public final TableField<ChatAndLinkRecord, Long> CHAT_ID = createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CHAT_AND_LINK.LINK_ID</code>.
     */
    public final TableField<ChatAndLinkRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>CHAT_AND_LINK.STATUS</code>.
     */
    public final TableField<ChatAndLinkRecord, Integer> STATUS = createField(DSL.name("STATUS"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    private ChatAndLink(Name alias, Table<ChatAndLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChatAndLink(Name alias, Table<ChatAndLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>CHAT_AND_LINK</code> table reference
     */
    public ChatAndLink(String alias) {
        this(DSL.name(alias), CHAT_AND_LINK);
    }

    /**
     * Create an aliased <code>CHAT_AND_LINK</code> table reference
     */
    public ChatAndLink(Name alias) {
        this(alias, CHAT_AND_LINK);
    }

    /**
     * Create a <code>CHAT_AND_LINK</code> table reference
     */
    public ChatAndLink() {
        this(DSL.name("CHAT_AND_LINK"), null);
    }

    public <O extends Record> ChatAndLink(Table<O> child, ForeignKey<O, ChatAndLinkRecord> key) {
        super(child, key, CHAT_AND_LINK);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public List<ForeignKey<ChatAndLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_8, Keys.CONSTRAINT_89);
    }

    private transient Chat _chat;
    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.CHAT</code> table.
     */
    public Chat chat() {
        if (_chat == null)
            _chat = new Chat(this, Keys.CONSTRAINT_8);

        return _chat;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.CONSTRAINT_89);

        return _link;
    }

    @Override
    @NotNull
    public ChatAndLink as(String alias) {
        return new ChatAndLink(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public ChatAndLink as(Name alias) {
        return new ChatAndLink(alias, this);
    }

    @Override
    @NotNull
    public ChatAndLink as(Table<?> alias) {
        return new ChatAndLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatAndLink rename(String name) {
        return new ChatAndLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatAndLink rename(Name name) {
        return new ChatAndLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public ChatAndLink rename(Table<?> name) {
        return new ChatAndLink(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row3<Long, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super Long, ? super Long, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super Long, ? super Long, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
